// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwkjukmpjbnrguijxhxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3a2p1a21wamJucmd1aWp4aHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NTc4OTYsImV4cCI6MjA1MTEzMzg5Nn0.RXkcRSRC4urnZwz6pgnVS4no0tjWT5o8FXPHgDNTDY8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);